# Generated by Django 5.2.8 on 2025-12-19 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('baileys', 'Baileys'), ('whatsapp_business', 'WhatsApp Business API')], default='twilio', max_length=50, verbose_name='Proveedor')),
                ('is_enabled', models.BooleanField(default=False, help_text='Activar/desactivar envío de mensajes', verbose_name='Habilitado')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Máximo de Reintentos')),
                ('retry_delay_minutes', models.IntegerField(default=5, verbose_name='Delay entre Reintentos (minutos)')),
                ('daily_message_limit', models.IntegerField(default=1000, help_text='0 = sin límite', verbose_name='Límite Diario de Mensajes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuración WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Plantilla')),
                ('message_type', models.CharField(choices=[('payment_confirmation', 'Confirmación de Pago'), ('shift_reminder', 'Recordatorio de Turno'), ('sanction_notice', 'Notificación de Sanción'), ('reservation_confirmation', 'Confirmación de Reserva'), ('meeting_reminder', 'Recordatorio de Reunión'), ('debt_reminder', 'Recordatorio de Deuda'), ('general', 'General')], max_length=50, verbose_name='Tipo de Mensaje')),
                ('template_content', models.TextField(help_text='Use {variable} para variables dinámicas. Ej: Hola {nombre}, su pago de {monto} Bs fue recibido.', verbose_name='Contenido de Plantilla')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Plantilla WhatsApp',
                'verbose_name_plural': 'Plantillas WhatsApp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(help_text='Formato: +591XXXXXXXX', max_length=20, verbose_name='Teléfono Destinatario')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Destinatario')),
                ('message_type', models.CharField(choices=[('payment_confirmation', 'Confirmación de Pago'), ('shift_reminder', 'Recordatorio de Turno'), ('sanction_notice', 'Notificación de Sanción'), ('reservation_confirmation', 'Confirmación de Reserva'), ('meeting_reminder', 'Recordatorio de Reunión'), ('debt_reminder', 'Recordatorio de Deuda'), ('general', 'General')], default='general', max_length=50, verbose_name='Tipo de Mensaje')),
                ('message_content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('external_message_id', models.CharField(blank=True, help_text='SID de Twilio u otro identificador', max_length=255, null=True, verbose_name='ID Externo')),
                ('related_payment_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Pago Relacionado')),
                ('related_reservation_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Reserva Relacionada')),
                ('related_sanction_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Sanción Relacionada')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='whatsapp_no_created_87cc5c_idx'), models.Index(fields=['status'], name='whatsapp_no_status_1ab8ed_idx'), models.Index(fields=['recipient_phone'], name='whatsapp_no_recipie_92d58b_idx'), models.Index(fields=['message_type'], name='whatsapp_no_message_1ed1d0_idx')],
            },
        ),
    ]
