# Generated by Django 5.2.8 on 2026-01-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_notif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='related_cuota_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID de Cuota Relacionada'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('payment_confirmation', 'Confirmación de Pago'), ('shift_reminder', 'Recordatorio de Turno'), ('sanction_notice', 'Notificación de Sanción'), ('reservation_confirmation', 'Confirmación de Reserva'), ('meeting_reminder', 'Recordatorio de Reunión'), ('debt_reminder', 'Recordatorio de Deuda'), ('cuota_payment', 'Pago de Cuota'), ('general', 'General')], default='general', max_length=50, verbose_name='Tipo de Mensaje'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='message_type',
            field=models.CharField(choices=[('payment_confirmation', 'Confirmación de Pago'), ('shift_reminder', 'Recordatorio de Turno'), ('sanction_notice', 'Notificación de Sanción'), ('reservation_confirmation', 'Confirmación de Reserva'), ('meeting_reminder', 'Recordatorio de Reunión'), ('debt_reminder', 'Recordatorio de Deuda'), ('cuota_payment', 'Pago de Cuota'), ('general', 'General')], max_length=50, verbose_name='Tipo de Mensaje'),
        ),
    ]
