# Generated by Django 5.2.8 on 2025-11-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('tipo', models.CharField(default='mensual', max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='pendiente', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='afiliados.afiliado')),
            ],
            options={
                'ordering': ['-periodo'],
                'unique_together': {('afiliado', 'periodo', 'tipo')},
            },
        ),
    ]
