# Generated by Django 5.2.8 on 2025-12-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('glosa', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('expirado', 'Expirado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('qr_string', models.TextField(help_text='Contenido raw del código QR')),
                ('imagen_base64', models.TextField(blank=True, help_text='Imagen en base64 para mostrar directo', null=True)),
                ('transaction_id', models.CharField(help_text='ID único de transacción (uuid)', max_length=100, unique=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
