# Generated by Django 5.2.8 on 2026-01-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('VIDEO_EXTERNO', 'Video Externo (YouTube/Link)')], default='IMAGEN', max_length=20)),
                ('archivo', models.FileField(blank=True, help_text='Para imágenes o videos cortos', null=True, upload_to='web_publica/multimedia/')),
                ('url_externa', models.URLField(blank=True, help_text='Para videos de YouTube o enlaces externos', null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contenido Multimedia',
                'verbose_name_plural': 'Galería Multimedia',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
