# Generated by Django 5.2.8 on 2026-01-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=20, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('hora_envio', models.TimeField(default='08:00', verbose_name='Hora de Envío')),
                ('destinatarios_whatsapp', models.TextField(blank=True, help_text='Separados por coma', verbose_name='Teléfonos WhatsApp')),
                ('destinatarios_email', models.TextField(blank=True, help_text='Separados por coma', verbose_name='Emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=20, verbose_name='Tipo de Reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('fecha_periodo', models.DateField(help_text='Fecha del día/semana/mes reportado', verbose_name='Fecha del Período')),
                ('contenido', models.TextField(verbose_name='Contenido del Reporte')),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='generado', max_length=20, verbose_name='Estado')),
                ('destinatarios_whatsapp', models.TextField(blank=True, help_text='Separados por coma', verbose_name='Teléfonos Destinatarios')),
                ('destinatarios_email', models.TextField(blank=True, help_text='Separados por coma', verbose_name='Emails Destinatarios')),
                ('mensajes_enviados', models.IntegerField(default=0, verbose_name='Mensajes Enviados')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['-fecha_generacion'], name='reportes_au_fecha_g_c45de4_idx'), models.Index(fields=['tipo', 'estado'], name='reportes_au_tipo_3771d7_idx')],
            },
        ),
    ]
