# Generated by Django 5.2.8 on 2026-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionreporte',
            name='tipo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('lunes_control', 'Control Lunes (Hojas Ruta)')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('lunes_control', 'Control Lunes (Hojas Ruta)')], max_length=20, verbose_name='Tipo de Reporte'),
        ),
    ]
