# Generated by Django 4.2.11 on 2026-10-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_auto', '0002_alter_configuracionreporte_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionreporte',
            options={'ordering': ['tipo'], 'verbose_name': 'Configuración de Reporte', 'verbose_name_plural': 'Configuraciones de Reportes'},
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='dia_mes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-28. Dejar vacío para cualquier día', null=True, verbose_name='Día del Mes'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dejar vacío para todos los días', null=True, verbose_name='Día de la Semana'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='fallos_consecutivos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fallos Consecutivos'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='formato_adjunto',
            field=models.CharField(choices=[('ninguno', 'Solo texto'), ('pdf', 'PDF'), ('excel', 'Excel'), ('ambos', 'PDF + Excel')], default='ninguno', max_length=10, verbose_name='Adjunto'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='incluir_kpis',
            field=models.BooleanField(default=False, help_text='Agrega indicadores financieros al reporte', verbose_name='Incluir KPIs'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='ultimo_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Envío Exitoso'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='ultimo_intento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Intento'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='adjuntos',
            field=models.JSONField(blank=True, default=list, verbose_name='Adjuntos'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='datos',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos Estructurados'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='destinatarios_fallidos',
            field=models.IntegerField(default=0, verbose_name='Destinatarios con Error'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Intentos de Envío'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='origen',
            field=models.CharField(choices=[('programado', 'Programado'), ('manual', 'Manual')], default='programado', max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='estado',
            field=models.CharField(choices=[('generado', 'Generado'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('omitido', 'Omitido')], default='generado', max_length=20, verbose_name='Estado'),
        ),
    ]
