# Generated by Django 4.2.11 on 2026-10-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_auto', '0003_alter_configuracionreporte_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='pendientes',
            field=models.JSONField(blank=True, default=list, verbose_name='Destinatarios Pendientes'),
        ),
        migrations.AlterField(
            model_name='configuracionreporte',
            name='tipo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('lunes_control', 'Control Lunes (Hojas Ruta)'), ('puntero_la_paz', 'Puntero La Paz (operativo)')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('lunes_control', 'Control Lunes (Hojas Ruta)'), ('puntero_la_paz', 'Puntero La Paz (operativo)')], max_length=20, verbose_name='Tipo de Reporte'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['tipo', 'fecha_periodo', 'origen'], name='rep_auto_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracionreporte',
            constraint=models.UniqueConstraint(fields=('tipo',), name='rep_auto_config_tipo_unico'),
        ),
        migrations.AddConstraint(
            model_name='configuracionreporte',
            constraint=models.CheckConstraint(check=models.Q(('dia_mes__isnull', True), models.Q(('dia_mes__gte', 1), ('dia_mes__lte', 28)), _connector='OR'), name='rep_auto_config_dia_mes_rango'),
        ),
    ]
