# Generated by Django 5.2.8 on 2025-11-30 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0004_afiliado_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroDirectorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('secretario_general', 'Secretario General'), ('secretario_relaciones', 'Secretario de Relaciones'), ('secretario_hacienda', 'Secretario de Hacienda'), ('secretario_actas', 'Secretario de Actas'), ('secretario_conflictos', 'Secretario de Conflictos'), ('secretario_deportes', 'Secretario de Deportes'), ('vocal', 'Vocal')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('concluido', 'Concluido')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_directorio', to='afiliados.afiliado')),
            ],
            options={
                'ordering': ['-fecha_inicio', 'cargo'],
            },
        ),
    ]
