# Generated by Django 5.2.8 on 2026-03-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0002_reunion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='acta_texto',
            field=models.TextField(blank=True, verbose_name='Contenido del Acta'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='acuerdos',
            field=models.TextField(blank=True, help_text='Resumen de puntos acordados', verbose_name='Acuerdos de la Reunión'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='documento_adjunto',
            field=models.CharField(blank=True, help_text='URL o ruta del acta escaneada', max_length=255, null=True),
        ),
    ]
