# Generated by Django 5.2.8 on 2025-11-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.CharField(max_length=30, unique=True)),
                ('fecha_emision', models.DateField()),
                ('estado', models.CharField(default='emitida', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('archivo_url', models.CharField(blank=True, max_length=255)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ruta', to='afiliados.afiliado')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
