# Generated by Django 5.2.8 on 2025-11-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojasruta', '0004_hojaruta_nro_nonunique'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='agente_parada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
