# Generated by Django 5.2.8 on 2026-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojasruta', '0005_hojaruta_agente_parada_hojaruta_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaruta',
            name='estado',
            field=models.CharField(db_index=True, default='emitida', max_length=20),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='fecha_salida',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
