# Generated by Django 5.2.8 on 2026-03-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0008_afiliado_ci_exp'),
        ('hojasruta', '0006_alter_hojaruta_estado_alter_hojaruta_fecha_salida'),
        ('rutas', '0004_set_prefijos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_salida', to='afiliados.afiliado')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_programados', to='rutas.ruta')),
            ],
            options={
                'ordering': ['fecha', 'orden'],
                'unique_together': {('fecha', 'afiliado', 'ruta')},
            },
        ),
    ]
