# Generated by Django 4.2.11 on 2026-08-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojasruta', '0007_turnosalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
