# Generated by Django 4.2.11 on 2026-08-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojasruta', '0008_hojaruta_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnosalida',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
