# Generated by Django 5.2.7 on 2025-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopago',
            name='dia_plazo',
            field=models.IntegerField(blank=True, help_text='Día de la semana (0=Lunes, 6=Domingo)', null=True),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='hora_fin_plazo',
            field=models.TimeField(blank=True, help_text='Hora de fin del plazo (ej: 22:00)', null=True),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='hora_inicio_plazo',
            field=models.TimeField(blank=True, help_text='Hora de inicio del plazo (ej: 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='monto_multa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de multa por pago fuera de plazo', max_digits=10),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='tiene_plazo',
            field=models.BooleanField(default=False, help_text='¿Este tipo de pago tiene plazo límite?'),
        ),
    ]
