# Generated by Django 5.2.8 on 2026-01-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_tipopago_dia_plazo_tipopago_hora_fin_plazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='saldo_anterior_gestion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo de la gestión anterior', max_digits=10),
        ),
    ]
