# Generated by Django 5.2.8 on 2026-01-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojasruta', '0005_hojaruta_agente_parada_hojaruta_fecha_salida'),
        ('tesoreria', '0003_pago_saldo_anterior_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='hoja_ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_tesoreria', to='hojasruta.hojaruta'),
        ),
    ]
