# Generated by Django 5.2.8 on 2026-03-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0004_pago_hoja_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'QR / Yape'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
