# Generated by Django 5.2.8 on 2026-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0006_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='banco',
            field=models.CharField(blank=True, help_text='Nombre del banco si es transferencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'QR / Yape'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='egreso',
            name='nro_operacion',
            field=models.CharField(blank=True, help_text='Número de operación / transacción', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='banco',
            field=models.CharField(blank=True, help_text='Nombre del banco si es transferencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='nro_operacion',
            field=models.CharField(blank=True, help_text='Número de operación / transacción', max_length=100, null=True),
        ),
    ]
