# Generated by Django 5.2.8 on 2026-04-11 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0007_egreso_banco_egreso_metodo_pago_egreso_nro_operacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_teorico', models.DecimalField(decimal_places=2, default=0, help_text='Total Ingresos - Total Egresos', max_digits=12)),
                ('saldo_real', models.DecimalField(decimal_places=2, help_text='Dinero físico real en caja', max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Saldo Real - Saldo Teórico', max_digits=12)),
                ('mes', models.CharField(blank=True, max_length=20, null=True)),
                ('anho', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='cerrado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anho', '-mes', '-fecha_fin'],
            },
        ),
    ]
