# Generated by Django 4.2.11 on 2026-04-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0008_arqueocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='detalle_efectivo',
            field=models.JSONField(blank=True, help_text='Desglose de billetes y monedas', null=True),
        ),
    ]
