# Generated by Django 5.2.8 on 2026-04-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0009_arqueocaja_detalle_efectivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egreso',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado/Completado'), ('anulado', 'Anulado')], default='aprobado', max_length=30),
        ),
        migrations.AddField(
            model_name='egreso',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='Justificación si el egreso es anulado', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='Justificación si el pago es anulado', null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('anulado', 'Anulado'), ('cancelado', 'Cancelado')], default='completado', max_length=20),
        ),
    ]
