# Generated by Django 5.2.8 on 2026-04-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0010_egreso_aprobado_por_egreso_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='justificacion_diferencia',
            field=models.TextField(blank=True, help_text='Justificación de la diferencia de caja', null=True),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='seguimiento_diferencia',
            field=models.TextField(blank=True, help_text='Seguimiento / acción tomada sobre la diferencia', null=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='auditado_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_auditados', to='tesoreria.arqueocaja'),
        ),
        migrations.AddField(
            model_name='pago',
            name='auditado_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_auditados', to='tesoreria.arqueocaja'),
        ),
    ]