# Generated by Django 5.2.8 on 2026-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0011_arqueocaja_justificacion_diferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='uuid',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]