# Generated by Django 5.2.8 on 2026-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0012_pago_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='uuid',
            field=models.CharField(default='', help_text='Identificador único del pago', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]