# Generated by Django 5.2.8 on 2026-03-05 18:48

import django.db.models.deletion
import encomiendas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hojasruta', '0006_alter_hojaruta_estado_alter_hojaruta_fecha_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tracking', models.CharField(default=encomiendas.models.generar_codigo_tracking, max_length=15, unique=True)),
                ('remitente_nombre', models.CharField(max_length=100)),
                ('remitente_ci', models.CharField(blank=True, max_length=20, null=True)),
                ('remitente_telefono', models.CharField(max_length=20)),
                ('destinatario_nombre', models.CharField(max_length=100)),
                ('destinatario_ci', models.CharField(blank=True, max_length=20, null=True)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Caja de ropa, Sobre, Repuestos', max_length=200)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Costo del envío', max_digits=8)),
                ('pagado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado (En Oficina)'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado')], default='registrado', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('hoja_ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas', to='hojasruta.hojaruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
