# Generated by Django 5.2.8 on 2025-11-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='afiliados.afiliado')),
            ],
            options={
                'ordering': ['placa'],
            },
        ),
    ]
