# Generated by Django 5.2.7 on 2025-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='indocumentado',
            field=models.BooleanField(default=False, help_text='Vehículo sin placa registrada (solo puede ir a Caranavi)'),
        ),
    ]
