# Generated by Django 5.2.7 on 2025-12-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_indocumentado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='es_convenio_caranavi',
            field=models.BooleanField(default=False, help_text='Vehículo de Convenio Caranavi (solo puede ir a La Paz)'),
        ),
    ]
