# Generated by Django 5.2.8 on 2025-12-27 18:30

import sistema.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_es_convenio_caranavi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=15, unique=True, validators=[sistema.validators.validate_placa_vehiculo]),
        ),
    ]
