# Generated by Django 5.2.8 on 2026-01-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0005_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('soat', 'SOAT'), ('inspeccion', 'Inspección Técnica'), ('seguro', 'Seguro Vehicular'), ('otro', 'Otro Documento')], max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alerta_enviada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Documentación de Vehículo',
                'verbose_name_plural': 'Documentaciones de Vehículos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilometraje', models.PositiveIntegerField(help_text='Kilometraje al momento del servicio')),
                ('tipo_servicio', models.CharField(choices=[('aceite', 'Cambio de Aceite'), ('frenos', 'Frenos'), ('llantas', 'Llantas / Alineación'), ('motor', 'Reparación de Motor'), ('electrico', 'Sistema Eléctrico'), ('limpieza', 'Limpieza / Estético'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taller', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Historial de Mantenimiento',
                'verbose_name_plural': 'Historiales de Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
