# Generated by Django 5.2.8 on 2025-11-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0004_afiliado_direccion'),
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='afiliados.afiliado')),
                ('referencia_asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sancion', to='asistencias.asistencia')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('afiliado', 'referencia_asistencia', 'tipo')},
            },
        ),
    ]
