# Generated by Django 5.2.8 on 2025-11-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_seed_destinos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='prefijo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
