# Generated by Django 5.2.7 on 2025-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_afiliado_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
