# Generated by Django 5.2.8 on 2025-12-27 18:30

import sistema.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_afiliado_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='ci',
            field=models.CharField(max_length=20, unique=True, validators=[sistema.validators.validate_ci_boliviano]),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[sistema.validators.validate_telefono_boliviano]),
        ),
    ]
