# Generated by Django 5.2.8 on 2026-01-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0005_alter_afiliado_ci_alter_afiliado_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='afiliados.afiliado')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
