# Generated by Django 5.2.8 on 2026-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0006_turnoagente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='estado',
            field=models.CharField(db_index=True, default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
