# Generated by Django 5.2.8 on 2026-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0007_alter_afiliado_estado_alter_afiliado_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='ci_exp',
            field=models.CharField(choices=[('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('TJ', 'Tarija'), ('CH', 'Chuquisaca'), ('BN', 'Beni'), ('PA', 'Pando')], default='LP', max_length=5, verbose_name='Expedido en'),
        ),
    ]
