# Generated by Django 5.2.8 on 2026-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_notificacion_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva', 'Nueva Reserva Online'), ('encomienda', 'Nueva Encomienda'), ('sistema', 'Alerta de Sistema'), ('vehiculo', 'Vencimiento Documentación')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Sistema',
                'verbose_name_plural': 'Alertas de Sistema',
                'ordering': ['-fecha'],
            },
        ),
    ]
