# Generated by Django 5.2.8 on 2026-01-12 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('login', 'Inicio de Sesión'), ('otro', 'Otro')], max_length=20)),
                ('tabla', models.CharField(max_length=50)),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
