# Generated by Django 4.2.11 on 2026-09-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_logauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='app_label',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='cambios_labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
