# Generated by Django 5.2.8 on 2025-11-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0003_afiliado_timestamps'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('fecha_viaje', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('afiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='afiliados.afiliado')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='rutas.ruta')),
            ],
            options={
                'ordering': ['-fecha_viaje'],
            },
        ),
    ]
