# Generated by Django 5.2.7 on 2025-12-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asiento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
