# Generated by Django 5.2.8 on 2025-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
