# Generated by Django 5.2.7 on 2025-12-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('permiso', 'Permiso'), ('atraso', 'Atraso')], default='presente', max_length=20),
        ),
    ]
