# Generated by Django 5.2.7 on 2025-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_remove_asistencia_observaciones_asistencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
